// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unicorp.App.Persistencia;

namespace Unicorp.App.Persistencia.Migrations
{
    [DbContext(typeof(AplicationContext))]
    partial class AplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Unicorp.App.Dominio.Pagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Entidad_bancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pago")
                        .HasColumnType("int");

                    b.Property<string>("Soporte_pago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarifa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Personas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_registro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_completo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Personas");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Servicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tecnico")
                        .HasColumnType("int");

                    b.Property<string>("Tarifa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("genera_cobroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("genera_cobroId");

                    b.ToTable("Servicio");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Servicios");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Administradores", b =>
                {
                    b.HasBaseType("Unicorp.App.Dominio.Personas");

                    b.HasDiscriminator().HasValue("Administradores");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Clientes", b =>
                {
                    b.HasBaseType("Unicorp.App.Dominio.Personas");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Membresia")
                        .HasColumnType("bit");

                    b.Property<int?>("TecnicosId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("genera_pagoId")
                        .HasColumnType("int");

                    b.Property<int?>("solicita_servicioId")
                        .HasColumnType("int");

                    b.HasIndex("TecnicosId");

                    b.HasIndex("genera_pagoId");

                    b.HasIndex("solicita_servicioId");

                    b.HasDiscriminator().HasValue("Clientes");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Tecnicos", b =>
                {
                    b.HasBaseType("Unicorp.App.Dominio.Personas");

                    b.Property<string>("Disponibilidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formacion_Academica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tarjeta_Profesional")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Tecnicos");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Detalle_de_Servicios", b =>
                {
                    b.HasBaseType("Unicorp.App.Dominio.Servicios");

                    b.Property<string>("Descripcion_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hora_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Detalle_de_Servicios");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Servicios", b =>
                {
                    b.HasOne("Unicorp.App.Dominio.Pagos", "genera_cobro")
                        .WithMany()
                        .HasForeignKey("genera_cobroId");

                    b.Navigation("genera_cobro");
                });

            modelBuilder.Entity("Unicorp.App.Dominio.Clientes", b =>
                {
                    b.HasOne("Unicorp.App.Dominio.Tecnicos", "Tecnicos")
                        .WithMany()
                        .HasForeignKey("TecnicosId");

                    b.HasOne("Unicorp.App.Dominio.Pagos", "genera_pago")
                        .WithMany()
                        .HasForeignKey("genera_pagoId");

                    b.HasOne("Unicorp.App.Dominio.Servicios", "solicita_servicio")
                        .WithMany()
                        .HasForeignKey("solicita_servicioId");

                    b.Navigation("genera_pago");

                    b.Navigation("solicita_servicio");

                    b.Navigation("Tecnicos");
                });
#pragma warning restore 612, 618
        }
    }
}
